export { default as Banner } from "./Banner"
export { default as Footer } from "./Footer"
export { default as Header } from "./Header"
export { default as ListHotel } from "./ListHotel"
export { default as PopularTravelCarousel } from "./PopularTravelCarousel"
export { default as Chart } from "./host/Chart"
export { default as Deposit } from "./host/Deposit"
export { default as TableHostRoom } from "./host/TableHostRoom"
export { default as Title } from "./host/Title"
export { default as CopyRight } from "./host/CopyRight"

